### ISSUE TITLE
MIR assertion failure after some recent updates

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#100]
Hi,

I was trying to apply the latest commits in MIR to Ravi, and I got this failure:

```
mir-gen-x86_64.c:2058: target_init: Assertion `0 == code' failed.
```

I am running on Xeon processor -Redhat 7.8

**Comment by vnmakarov** [comment]
Thank you for reporting this.  I can not reproduce it but I suspect this is because of some specific way MIR API usage.

I'll try to fix it anyway.

**Comment by dibyendumajumdar** [comment]
I can try to generate a dump of the code that is giving me this assertion failure.

**Comment by dibyendumajumdar** [comment]
Hi @vnmakarov 

This issuse seems to be becaue I am calling     

```
MIR_gen_init (ctx); 
```

everytime I compile a module.
Since this calls target_init - it seems that the second time it fails.
I can see this because it is calling:

```
  MIR_proto_t proto = _MIR_create_proto (gen_ctx->ctx, "movdqa", 1, &res, 1, FALSE, args);
  code = _MIR_register_unspec_insn (gen_ctx->ctx, proto);
```

In target_init - so the second time it is adding the proto again to the array.

**Comment by vnmakarov** [comment]
> I thought I am supposed to call MIR_gen_init() everytime I compile a module. Is this not the case?

It is better to call MIR_gen_init once for given context as it permits to avoid a lot of necessary allocations and initializations.  So it is faster especially if you compile a lot of small functions.

In any case I've just fixed the problem.  So MIR_gen_init can be called more once now for given context.

Thank you for finding a reason for the issue.

**Comment by dibyendumajumdar** [comment]
Thank you
