### ISSUE TITLE
Question: Trying to understand solve_dataflow ()

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#106]
Hi @vnmakarov 

In `solve_dataflow()` there is this section:

```
        if (forward_p) {
          for (e = DLIST_HEAD (out_edge_t, bb->out_edges); e != NULL;
               e = DLIST_NEXT (out_edge_t, e))
            if (bitmap_set_bit_p (bb_to_consider, e->dst->index)) VARR_PUSH (bb_t, pending, e->dst);
        } else {
          for (e = DLIST_HEAD (in_edge_t, bb->in_edges); e != NULL; e = DLIST_NEXT (in_edge_t, e))
            if (bitmap_set_bit_p (bb_to_consider, e->src->index)) VARR_PUSH (bb_t, pending, e->src);
        }
```

I am trying to understand the line:

```
 if (bitmap_set_bit_p (bb_to_consider, e->src->index)) VARR_PUSH (bb_t, pending, e->src);
```

Initially I was puzzled as it is an if condition so I was wondering where is the bit being set? 

Then I saw the code for `bitmap_set_bit_p ()`:

```
static inline int bitmap_set_bit_p (bitmap_t bm, size_t nb) {
  size_t nw, sh;
  bitmap_el_t *addr;
  int res;

  bitmap_expand (bm, nb + 1);
  addr = VARR_ADDR (bitmap_el_t, bm);
  nw = nb / BITMAP_WORD_BITS;
  sh = nb % BITMAP_WORD_BITS;
  res = ((addr[nw] >> sh) & 1) == 0;
  addr[nw] |= (bitmap_el_t) 1 << sh;
  return res;
}
```

So this function not only sets a bit - it also returns a value. It seems to be returning true if the bit was not set.
So that means this function sets a bit and also says whether the bit was previously unset - implying that this bit is being set for the first time? Is this correct?

Thanks and Regards
Dibyendu

**Comment by vnmakarov** [comment]
> So this function not only sets a bit - it also returns a value. It seems to be returning true if the bit was not set.
> So that means this function sets a bit and also says whether the bit was previously unset - implying that this bit is being set for the first time? Is this correct?

Yes, it is a standard approach for bitset implementation in compilers.  The design might look counter-intuitive.  Some operations (like bitmpap_ior) can be expensive.  Frequently you need to know that the result is changed.  Combining the 2 operation into one can speed up code significantly.   And usually bitmap code is crtical in compilers for performance.

**Comment by dibyendumajumdar** [comment]
Okay thank you!
