### ISSUE TITLE
Some problem with the sieve example

### ISSUE THREAD

**Issue by zhuzilin** [vnmakarov/mir#107]
Thank you for your work on providing a fast light weight jit! As I was playing with some c examples, I notice that there are some problem with the sieve example provided in the readme. It is not the exact algorithm used to count the number of primes less or equal to `SieveSize`. For example, if we change the `SieveSize` to 100, function will return 45, while it should be 25. This doesn't affect its role as a benchmarking tool but may cause a little confusion to the new comer. I'd like to submit a pr to fix it if you like :).

FYI, the correct algorithm should be:
```c
int sieve (int n) {
  int i, k, prime, count, iter;
  char flags[SieveSize];

  for (iter = 0; iter < n; iter++) {
    count = 0;
    for (i = 0; i < SieveSize; i++) flags[i] = 1;
    for (i = 1; i < SieveSize; i++)
      if (flags[i]) {
        prime = i + 1;
        for (k = i + prime; k < SieveSize; k += prime) flags[k] = 0;
        count++;
      }
  }
  return count;
}
```

**Comment by vnmakarov** [comment]
> FYI, the correct algorithm should be:

Thank you for pointing this out.  I took it from somewhere w/o checking the algorithm but I can not remember the source.

 I've fixed all wrong sieve programs in the repository to use the right algorithm.
