### ISSUE TITLE
Improve support for zero length structs and arrays in C2M

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#117]
I've a C code generator that in some edge cases needs to emit empty structs or structs with zero length arrays, usually works fine on GCC/Clang/TCC, but on C2M I get errors, simple test case:

```C
typedef struct {} Foo;
typedef struct {int data[0];} Boo;

void f(Foo foo, Boo b) {}

int main() {
    Boo b = {};
    f((Foo){}, b);
    return 0;
}
```

The above compiles fine in GCC/Clang/TCC without warnings or errors, while in C2M I get:

```
test.c:1:9: warning -- empty struct/union
test.c:7:9: syntax error on identifier (expected ';'):
test.c:7:9: syntax error on identifier (expected '<statement>'):
test.c:2:26: array size should be positive
```

Note: Using `int data[0];` inside structs is no standard C, the correct would be `int data[];` however in all compilers I've tried the latter is only allowed when the struct has other fields, thus using `int data[0];` is intentional and supported by GCC/Clang.

**Comment by vnmakarov** [comment]
Ok.  I can implement this extension.  I already did this for empty structures (there is a test for this).  So I can do this for arrays too.  Probably it will be done in a month.

**Comment by edubart** [comment]
Great! I want to emphases that the issue is not just zero length arrays, but compound literals for zero empty structs are not working too, trimmed test case:

```C
typedef struct {} Foo;

void f(Foo foo) {}

int main() {
    f((Foo){});
    return 0;
}
```

```
test.c:1:9: warning -- empty struct/union
test.c:6:13: syntax error on } (expected '<statement>'):
test.c:6:14: syntax error on ) (expected '<statement>'):
```

**Comment by vnmakarov** [comment]
I've just committed a patch fixing this issue: cd3bc78d9bd7fc7faabd1105508f6c3f1475b0a6

**Comment by edubart** [comment]
Thanks, it worked! It just generates warnings now but runs fine. Is there a way to disable warnings in C2M? Would be good if there was a `-w` flag to disable all warnings.
