### ISSUE TITLE
Question: What happens on integer overflow?

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#119]
How are MIR operations defined in the following situations?

* Signed integer overflow (eg `INT_MAX + 1`)
* Division by zero (eg `x/0`)
* Division overflow (eg `(-INT_MAX - 1)/-1`)

All undefined?

From what I've checked running on my x86_64 division overflow and division by zero crashes with `SIGFPE, Arithmetic exception` and integer overflow looks like to wrap around following twos-complement rule. But is this defined or depends on the architecture?
For example `x/0` in RISC-V is defined as `-1`, if one day MIR supports RISC-V this means that `x/0` will be defined as `-1`?

Side note: I compile my C programs with `-fwrapv` to wrap around integer arithmetic operations following two-complements rule, this minimizes undefined behaviors, would be good to be able to do the same with MIR or if MIR could assure this the default behavior. From what I know implementing this is just a matter of casting to unsigned integers when doing signed operations and often there is no cost.

**Comment by vnmakarov** [comment]
MIR assumes two-complement arithmetic therefore some instructions are absent (please see MIR.md file).  C/C++ standards will assume 2-complement arithmetic too.  Most architectures uses 2-complement arithmetic (including all ones supported by MIR).  I am not going to support architectures without 2-complement arithmetic.  I don't know any modern architectures without such arithmetic.  Last architecture without 2-complement arithmetic I used was BESM-6.  

I'd like rather avoid to answer to other questions now.  So right now it can be treated as undefined.

In the future, I'll have more definite answer.

**Comment by edubart** [comment]
Okay, thanks!

**Comment by fweimer** [comment]
The other question is whether MIR assumes that integer arithmetic does not overflow. Other compilers implement several optimizations which assume that it does not, which means that at the C level, there isn't really two's complement arithmetic, although the underlying hardware does not behave that way, of course.
