### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by Pombal** [vnmakarov/mir#120]
Hi, what are the changes necessary to build from source on windows with visual studio (not mingw or cygwin)?

**Comment by logzero** [comment]
@warvstar wrote a CMake file which you should be able to use to generate a MSVC solution?
https://github.com/warvstar/mir/blob/master/CMakeLists.txt

It probably should be added to mir.

**Comment by Pombal** [comment]
Thanks @logzero, this is great. Would be good to add complete windows support to main.

**Comment by logzero** [comment]
I've git it to compile remotely using github actions with some try and error lol.
https://github.com/logzero/mir/tree/cmake

Will create a clean pull request once I've cleared a few bits with vnmakarov.

**Comment by Pombal** [comment]
What a legend, I'll switch to your branch in the meantime.
I did some of the same work but it was very ad-hoc for what I needed, this is much more systematic.

**Comment by Pombal** [comment]
@logzero There are includes such as `unistd.h` that don't compile on your branch, for example in mir-tests/readme-example.c.
Another issue is that running that test crashes while executing the function `MIR_interp` on line 73.

I wanted to leave a comment on your branch but didn't find a way to do it.

**Comment by rofl0r** [comment]
> @logzero There are includes such as unistd.h that don't compile 

microsoft's got a seat on the C committee, yet they still haven't managed to add unistd.h to their compiler?
looks like they use their seat only to sabotage the C standard by pushing through bogus extensions like [annex K](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1967.htm).

**Comment by logzero** [comment]
@Pombal haven't looked at tests yet, just compiling c2m.

**Comment by logzero** [comment]
I've got a wip branch adding interp and gen tests to cmake and running them using ctest.
https://github.com/logzero/mir/tree/ctest1

cmake -G 'Visual Studio 16 2019' -A x64 -DBUILD_TESTING=ON
cmake --build . --config Release
ctest --extra-verbose --output-on-failure

The results are not great.

Help from MSC users would be greatly appreciated. Feel free to submit pull requests for review.

**Comment by logzero** [comment]
I've got a primary set of the tests to run. Closing this issue.
