### ISSUE TITLE
MSC compiler and options define in c2mir

### ISSUE THREAD

**Issue by logzero** [vnmakarov/mir#122]
Unlike mingw windows compiler requires to use windows.h instead of specific headers, something I hoped to avoid.

windows.h causes issues with #define options c2m_ctx->options in c2mir.c.

@vnmakarov what name would you prefer instead? I've renamed it to c2m_options in my cmake wip branch.
https://github.com/logzero/mir/tree/cmake

Btw I am using a separate winbuild.yml action. Is it acceptable or should it be merged into build.yml?
https://github.com/logzero/mir/blob/cmake/.github/workflows/winbuild.yml

**Comment by vnmakarov** [comment]
> @vnmakarov what name would you prefer instead? I've renamed it to c2m_options in my cmake wip branch.
> https://github.com/logzero/mir/tree/cmake
> 

c2m_option is ok for me.

> Btw I am using a separate winbuild.yml action. Is it acceptable or should it be merged into build.yml?
> https://github.com/logzero/mir/blob/cmake/.github/workflows/winbuild.yml

Yes, if the current trunk is passing it, I'd like to merge it into build.yml.

Thank you again for working on windows port.

Btw, I implemented call ABI compatibility for c2m for all targets except win64.  I did not look into C windows call ABI (e.g. how small aggregates are passed and returned).  Probably win64 needs some work here too.  I'll look into this when I have more time.
