### ISSUE TITLE
fseek/ftell with fopen (name, "r")

### ISSUE THREAD

**Issue by logzero** [vnmakarov/mir#130]
In mir-tests/test-read.h

fread (str, 1, len, f) != len

is true with MSC compiler.

Not sure what the best approach here would be.

**Comment by vnmakarov** [comment]
> Not sure what the best approach here would be.

I think the right `#if` for MSC would work.  `fread` condition tests only that we read all the text whose length is found by previous fseek/ftell.

**Comment by logzero** [comment]
Okay, I just ifdefed the read length check out for MSC.

I've got adt-test, mir-test, io-test, scan-test, interp-test, gen-test my ctest1 branch.

The only failing tests are test12 (multiple return vals) and gen-test13 (segfault). I've commented them out for now.

I'll be submitting pull requests for review tomorrow.
