### ISSUE TITLE
I think that it would be useful if the c2mir was also treated as a library / API, which means exposing some api for clients to call.

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#14]
I think that it would be useful if the c2mir was also treated as a library / API, which means exposing some api for clients to call. My suggestion is something like:

```
MIR_module_t 
MIR_compile_C_module(MIR_context_t ctx, int argc, const char *argv[], const char *inputbuffer);
```
That is, given an optional buffer plus command line arguments, generate a module and return it.

Raising this as a separate issue.

_Originally posted by @dibyendumajumdar in https://github.com/vnmakarov/mir/issues/10#issuecomment-546735288_

**Comment by vnmakarov** [comment]
I am agree. If people want to start use c2mir compiler as interface language to their JITs, we need to provide it as library, remove global state, and improve error processing.

I am only going to provide this as a separate layer.  I think in some cases, people will want only MIR layer because of faster compilation and smaller size.

This work will also require decoupling c2mir driver and defining what options should be used by driver and library itself.  I don't know when it will be done (right now I am busy with another project until April) but I hope it will be done before the year end.

**Comment by vnmakarov** [comment]
I removed the global state from C2MIR and added error processing to remove all allocated memory in case of compilation errors.  I also separated C2MIR driver to use C2MIR as a separate program. 

So I am moving to the direction to make C2MIR a library.  Probably the current interface (`c2mir.h`) is not final and it will change but not radically.

  Removing the global state slows down the compiler by 10%.  So I am going to work to decrease this compilation speed degradation.

**Comment by dibyendumajumdar** [comment]
wow, amazing!

**Comment by dibyendumajumdar** [comment]
Thanks a lot for looking at this so soon. Really appreciated.

I have a few questions:
1. What is the purpose of module_num? 
2. I presume each call to c2mir_compile() results in a single module?
3. How can we get hold of the module just compiled? 

Thank you

**Comment by vnmakarov** [comment]
> Thanks a lot for looking at this so soon. Really appreciated.
> 
> I have a few questions:
> 
>     1. What is the purpose of module_num?
> 

Module has a name `M<number>`, where `<number>` is value of `module_num`

>     2. I presume each call to c2mir_compile() results in a single module?
> 

Yes, it translates what could be considered one C file and generate one MIR module.

>     3. How can we get hold of the module just compiled?
> 
It is the last module in the context module list.  To reach it you can use `DLIST_TAIL (MIR_module_t, *MIR_get_module_list (ctx))`.  If unique numbers are used for modules, you could find them by the name in the module list.

The current interface is just first version of separation of compiler itself and the driver.  If you have questions about c2mir compiler interface, `c2mir-driver.c` would be the first place to look at.

**Comment by dibyendumajumdar** [comment]
Closing as library api now available
