### ISSUE TITLE
Will there be support for Windows x64 abi?

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#15]
I had assumed the plan is to only support Unix like systems, but I saw the use of WIN32 conditional logic .... is there any plan to support the Win32 X64 calling convention?

**Comment by vnmakarov** [comment]
Yes, I'd like to make MIR more portable, implementing other ABIs and different target code generation.  It would be interesting for me to port MIR to aarch64, ppc64, mips64, and RISC-V (in this order).  Although I don't know when it will be done.

**Comment by dibyendumajumdar** [comment]
Can MIR be used on Win64 via mingcc or cygwin?

**Comment by vnmakarov** [comment]
> Can MIR be used on Win64 via mingcc or cygwin?

I am going to use MinGW to compile MIR code on Win64 when I start work on Win64 port.  It will require to implement additionally a bit different call ABI than currently used x86-64 one.

**Comment by warvstar** [comment]
Here are some of the changes I made to make this work on Windows, without mingw. It should compile with clang or msvc.
https://github.com/warvstar/mir

**Comment by dibyendumajumdar** [comment]
@warvstar Nice. I suspect though that until MIR handles Win64 calling convention, the JIT compiled code will not work correctly.
