### ISSUE TITLE
Question: Compile micropython to MIR for a simple Python JIT

### ISSUE THREAD

**Issue by wolfv** [vnmakarov/mir#158]
Hi, 

I am playing around a bit with MIR (mostly for fun) to see what is possible, and to learn more about JIT's.

I was wondering if you'd think it would be possible (and worthwhile) to compile the C implementation of something like Micropython to MIR and then use that to create some sort of (Micro)Python-JIT?
And later on, maybe try the "real" CPython?

**Comment by vnmakarov** [comment]
The original MIR project goal is to create a MRuby/CRuby light-weight JIT.  CPython is not different from CRuby with the point of view of  MIR usage for implementing a good JIT.

I did not start a real work on implementing a MIR-based JIT for Ruby yet and I expect some changes will be needed to MIR project to be successful with this goal.  It is an iterative process.

Although some people were already successful with using MIR for JIT implementations.  The best example is Ravi implementation (https://github.com/dibyendumajumdar/ravi).

As for micropython JIT, usage of MIR might be too heavy for this.  Micropython site advertises 256KB code space and 16KB RAM.  It is too big constraint for MIR usage.

I encourage anyone to try MIR as a JIT compiler and provide me some feedback.  This feedback would help MIR development and JIT implementations based on it.

**Comment by wolfv** [comment]
Sure, I was referring to MicroPython only as a simpler target that should be easier to compile and experiment with (not for serious usage). Thanks for pointing me at Ravi, I'll have a look. I'll report back if I get something interesting to work!
