### ISSUE TITLE
c2m segfaults on malformed declaration in release mode

### ISSUE THREAD

**Issue by fermian** [vnmakarov/mir#166]
This code segfaults c2m in release mode without showing any errors:

```
a {
```

GDB trace:

```
(gdb) r ../mir-errors/segfault-on-release.c
Starting program: /home/user/mir/c2m ../mir-errors/segfault-on-release.c
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7c4e700 (LWP 1750)]

Thread 2 "c2m" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7c4e700 (LWP 1750)]
0x000055555559e134 in transl_unit (no_err_p=0, c2m_ctx=0x555555671260) at c2mir/c2mir.c:5185
5185	      for (p = NL_HEAD (param_list->u.ops); p != NULL; p = NL_NEXT (p)) {
(gdb) 
```

In debug mode, it crashes with assertion failed. Is this check elided in release mode?

```
c2m: c2mir/c2mir.c:5183: transl_unit: Assertion `func != NULL && func->code == N_FUNC' failed.
Aborted
```

**Comment by rofl0r** [comment]
probably autoconf adds -DNDEBUG for release mode, which prevents assert from being compiled in.

**Comment by fermian** [comment]
Shouldn't this be an error instead of an assertion?

**Comment by vnmakarov** [comment]
> This code segfaults c2m in release mode without showing any errors:
> 
> ```
> a {
> ```

Thank for the test.  I really appreciate such small tests.

I have plans to use csmith for `c2m`.  I think it will help to find analogous bugs you are reporting.

In any case, I've fixed the bug.  The changes are in the master branch now.

5dbe37c920c92ef0975d49aafe0e183f26018e42
70d707daa417263887265388a881b0bf8ef76fd6
077cebf7f5a9cb794db72f22df3eb3f296b9e64b

**Comment by fermian** [comment]
> I have plans to use csmith for `c2m`. I think it will help to find analogous bugs you are reporting.

👍 

I used [afl-compiler-fuzzer](https://github.com/agroce/afl-compiler-fuzzer) to find them, I think you've fixed all of the crashes I found after 1 hour of fuzzing.
