### ISSUE TITLE
Allow using `(void)` for unused variables.

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#184]
It's common in C to use `(void)anything;` to discard unused expressions, this makes C compilers such as Clang/GCC suppress unused variables warnings, but this is not working for all variable types in C2M, example:

```C
typedef struct Foo {int x;} Foo;
int main(int argc, char** argv) {
  Foo foo;
  (void)foo;
  return 0;
}
```

The above code fails with error `conversion of non-scalar value requested`, while this compiles fine on GCC/Clang.

**Comment by edubart** [comment]
I am facing this issue with various C libraries that I am attempting to check if C2M works.

**Comment by vnmakarov** [comment]
The following commits were added to solve the issue:

https://github.com/vnmakarov/mir/commit/ce433457c467276c14dba62f14daf678ca2c4b3e
https://github.com/vnmakarov/mir/commit/2c0d8b43d7d16609a48404e0cccecae1d376b01b

**Comment by edubart** [comment]
The fix worked, thanks!
