### ISSUE TITLE
Different NaN behavior between interpreted and machine code

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#186]
The following tests checking NaN semantics, fails with `-eg` but not with `-ei` on C2M:

```C
#include <assert.h>
#include <stdio.h>

static double mynan = 0.0/0.0;

int main(int argc, char** argv) {
  assert(mynan != mynan);
  assert(!(mynan == mynan));
  assert(!(mynan < mynan));
  assert(!(mynan <= mynan));
  assert(!(mynan > mynan));
  assert(!(mynan >= mynan));
  printf("OK!\n");
  return 0;
}
```

Output:
```
➜ c2m test.c -ei
OK!
➜ c2m test.c -eg
c2m: test.c:9: main: Assertion `!(mynan < mynan)' failed.
Aborted (core dumped)
```

**Comment by vnmakarov** [comment]
Thank you for the test case.  It helped me find that I am wrongly dealing with unordered floating point numbers on x86-64.  The fix can be easy but the right fix (with better performance) can take some time.  But I hope to fix this in the right way on the next week.

**Comment by vnmakarov** [comment]
I've committed 
https://github.com/vnmakarov/mir/commit/02a6c4c81a046374da1a2f1777c1ee3115c9d1ec
and
https://github.com/vnmakarov/mir/commit/56b13220933327dc07b32fad4158db16663197bd
to fix this bug.

**Comment by edubart** [comment]
It worked, thanks!
