### ISSUE TITLE
Crash on array cast assignment

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#189]
The following example crashes with C2M, but not with GCC/Clang/TCC:

```c
#include <assert.h>

typedef struct Boo {float value;} Boo;
typedef struct Foo {Boo boos[4];} Foo;
typedef struct {Boo v[4];} Boo_arr4;

int main() {
  Foo foo;
  (*(Boo_arr4*)foo.boos) = (Boo_arr4){{(Boo){.value = 1.0f}}};
  assert(foo.boos[0].value == 1.0f);
  assert(foo.boos[1].value == 0.0f);
  return 0;
}
```

I have some C code gen that casts array in this style (the left hand side), so fixed arrays can be passed, copied, and assigned by value, this usually works fine on GCC/Clang/TCC.

```
$ c2m test.c
Segmentation fault (core dumped)
```

**Comment by vnmakarov** [comment]
Thank you for reporting many issues.  I'll  work on fixing them.  Here is the fix for given issue:

https://github.com/vnmakarov/mir/commit/f6c695f1d95f393cad61b967bd61ebf7b80d7855

**Comment by edubart** [comment]
It worked, thanks!
