### ISSUE TITLE
[C2M] C comments parsing error

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#19]
The parser confuses when using multiples `*` in a comment, the following:
```C
/**** TEXT ****/
int main(int argc, char **argv) {return 0;}
```

Outputs:
```
unfinished comment
cannot link program w/o main function
```

But it should parse and compile with no errors.

**Comment by vnmakarov** [comment]
Thank your for reporting this.  I really appreciate your active feedback for MIR-project.  I'll fix it in a couple of days.

**Comment by vnmakarov** [comment]
I've fixed.  The fix is in the repository.

**Comment by rofl0r** [comment]
https://github.com/vnmakarov/mir/commit/3978d59bf6cb45bacb73b4ae00bfef8220a9f580 <- adding commit hash of the fix for reference.
