### ISSUE TITLE
[C2M] Complete syntax for designated initializer is not supported yet

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#191]
I am including some C headers that have the following idiom, I am not sure if this is a standard C or extension yet, but the following usually works fine on GCC/Clang/GCC:

```c
typedef struct Boo {
  float x;
} Boo;

typedef struct Foo{
  Boo data[4];
} Foo;

int main() {
  Foo foo = (Foo){
    .data[0] = {0}
  };
  return 0;
}
```

It fails with:
```
test.c:11:11: array index in initializer for non-array
```

Ignore this if it's an unplanned extension.

**Comment by edubart** [comment]
While refactoring code using a syntax like above, I've found a crash related:

```C
typedef struct Coo {
  float size;
} Coo;

typedef struct Boo {
  Coo coo[4];
} Boo;

typedef struct Aoo {
  Boo boo;
} Aoo;

int main() {
  Aoo aoo = (Aoo){
    .boo = {
      .coo = {{
        .size = 0,
      }},
    },
  };
  return 0;
}
```

```
c2m test.c
Segmentation fault (core dumped)
```

**Comment by edubart** [comment]
> While refactoring code using a syntax like above, I've found a crash related:

Since commit f6c695f1d95f393cad61b967bd61ebf7b80d7855 the mentioned crash was fixed, so I am removing crash from the issue.

What remains in this issue is the complete support for designated initializer, I've looked up the C11 spec, and seems like the syntax is not an extension, and is available since C99.

See https://port70.net/~nsz/c/c11/n1570.html#6.7.9 for the C11 specification, in the syntax spec you can spot the `designator-list` , informing that designed initializers supports multiple designators. As example the following code should parse and compile according to C11 spec:

```c
typedef struct C { int x; } C;
typedef struct B { C c; C cs[4]; } B;
typedef struct A { B b; B bs[4]; } A;

int main() {
  A a1 = (A){.b.c.x = 1};
  A a2 = (A){.bs[0].c.x = 1};
  A a3 = (A){.bs[0].cs[0].x = 1};
  A a4 = (A){.bs = {[0].cs[0].x = 1, [1].cs[0].x = 2}};
  return 0;
}
```

The above compiles with `gcc -std=c99 -pedantic`, but fails with C2M. I've encountered some C libraries that uses this syntax and fails to compile with C2M.

**Comment by vnmakarov** [comment]
I've committed the following to solve the problem:
https://github.com/vnmakarov/mir/commit/24fd8796634d1bb72195ba5eee574ef6beb615a9
https://github.com/vnmakarov/mir/commit/98563fa8253cca719ac556b0e2f34f1a4639786a

**Comment by edubart** [comment]
The fix worked, thanks!

But after testing it I've faced another problem, so I've created the issue https://github.com/vnmakarov/mir/issues/198 .
