### ISSUE TITLE
[C2M] Compilation fails when returning from a if else statement

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#192]
The following test case fails to compile:

```c
typedef struct vec2 {
  double x,y;
} vec2;

static inline vec2 vec2_add(vec2 a, vec2 b) {
  if(1) {
    return (vec2){a.x+b.y, a.y+b.y};
  } else {
    return (vec2){a.x+b.y, a.y+b.y};
  }
}

int main() {
  return 0;
}
```

Error:
```
func vec2_add: in instruction 'ret': number of operands in return does not correspond number of function returns. Expected 2, got 1
```

Removing the `if` it compiles.

**Comment by vnmakarov** [comment]
The following commits are for fixing the issue:

https://github.com/vnmakarov/mir/commit/0c0edaf6e41277d460327c6bfda8541769952a46
and
https://github.com/vnmakarov/mir/commit/7d8660442ba99c606b60373c03721135d05df23a

**Comment by edubart** [comment]
It worked, thanks!
