### ISSUE TITLE
[C2M] Macros with `\` on CR-LF line breaks fails to parse

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#194]
I was testing this file https://github.com/orangeduck/mpc/blob/master/mpc.c with C2M, and it fails to parse due to the following macro:

```c
#define MPC_PRIMITIVE(x) \
  if (x) { MPC_SUCCESS(r->output); } \
  else { MPC_FAILURE(NULL); }
```

The problem is that that file uses CR-LF line breaks, when saving the file with LF line breaks looks like it fixes the issue.

**Comment by vnmakarov** [comment]
The following were commits for solving the issue:
https://github.com/vnmakarov/mir/commit/b31b9d787154bc65bb0f7a762eefb0011a39c7af
https://github.com/vnmakarov/mir/commit/6d490ff08759d7ed3c81089c4bdb6de618b12fdc

I am not sure that git will keep CR in the test.

**Comment by edubart** [comment]
The fix worked, thanks!
