### ISSUE TITLE
[C2M] Crash when calling a deference to a function double pointer

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#197]
The following test case makes C2M crash:

```c
#include <assert.h>
static int f() { return 1; }
typedef int (*F)();
static F pf = &f;
static F* ppf = &pf;
int main(int argc, char** argv) {
  assert((*ppf)() == 1);
}
```

Output:
```
c2m test2.c -eg
test2.c:5:18: warning -- incompatible types in assignment to a pointer
Segmentation fault (core dumped)
```

By the way, all the recent issues I've created I have found on occasion while attempting to make the language I am working on to pass all tests with C2M. So I am not trying to break C2M, I'm just trying to make it work with my C code generator.

**Comment by vnmakarov** [comment]
The following was committed for the issue:
https://github.com/vnmakarov/mir/commit/016dc2546d4b61bf2a1189d2891d7e6c275f3663
https://github.com/vnmakarov/mir/commit/90a6c70b22207ad870fc3dce95bd662bb3e60313

**Comment by edubart** [comment]
The fix works for me, thanks!
