### ISSUE TITLE
[C2M] Designed initializer misbehaves when out of order

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#198]
The following test case fails:
```c
#include <assert.h>

typedef struct Foo {
    int a;
    int b;
    int c;
} Foo;

int main() {
    Foo foo1 = {
        .a = 1,
        .b = 2,
        .c = 3,
    };
    assert(foo1.a == 1);
    assert(foo1.b == 2);
    assert(foo1.c == 3);

    Foo foo2 = {
        .b = 2,
        .a = 1,
        .c = 3,
    };
    assert(foo2.a == 1);
    assert(foo2.b == 2);
    assert(foo2.c == 3);
    return 0;
}
```

```
$ c2m test.c -eg
c2m: test.c:25: main: Assertion `foo2.b == 2' failed.
Aborted (core dumped)
```

I've just swapped the fields order in the initialization of `foo2`.

**Comment by vnmakarov** [comment]
I've committed the following for this issue:

https://github.com/vnmakarov/mir/commit/add8e647030f29667ccca63cbda00812fdd28673
https://github.com/vnmakarov/mir/commit/dc4f3c22fc9c4fffc341d4a0d2a3c85e0f985f51
https://github.com/vnmakarov/mir/commit/0547a03e35b7cf78ce588e1ee8736c0bc7bc3eba

**Comment by edubart** [comment]
The fix worked for me. With this and the previous fixes I was able to run a big C app with about 60k lines of C.
Many thanks for giving attention for the various recent bug reports I made and fixing them quickly!
