### ISSUE TITLE
[C2M] Crash or assertion in uncommon array pointer

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#199]
I found this piece of code while using [stb_vorbis](https://github.com/nothings/stb/blob/master/stb_vorbis.c), I've trimmed down the issue to the following example:

```c
#include <stdlib.h>
#include <assert.h>

typedef struct Residue {
   short (*residue_books)[8];
} Residue;

int main() {
    Residue r;
    Residue* pr = &r;
    void *p = malloc(sizeof(pr->residue_books[0]) * 10);
    pr->residue_books = (short (*)[8]) p;
    for(int i=0;i<10;++i)
        for(int j=0;j<8;++j)
            pr->residue_books[i][j] = 0xffff;
    assert(p == pr->residue_books);
    free(pr->residue_books);
    return 0;
}
```

Output:
```
$ c2m t.c -ei
Segmentation fault (core dumped)
$ c2m t.c -eg
c2m: t.c:16: main: Assertion `p == pr->residue_books' failed.
Aborted (core dumped)
```

I've never seen such syntax for pointer and arrays before, this kind of code should be uncommon.
The example compiles and runs fine in GCC/Clang. On C2M looks like the array pointer is being overwritten, the `pr->residue_books` pointer becomes `0xffffffffffffff` after the for loop.

**Comment by vnmakarov** [comment]
I've committed the following to solve the issue:

https://github.com/vnmakarov/mir/commit/fef226f119e15f2cdbc6ed45b9d8f17b85a1f993
https://github.com/vnmakarov/mir/commit/6ce1854e2b0fa28f1f8b22a2fb58069277ed6424

**Comment by edubart** [comment]
The fix works for on my tests, thanks!
