### ISSUE TITLE
[Feature request] Use third party libraries

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#20]
I've noted in the code that just symbols from `libm` and `libc` is available. Would be nice to use third party libraries with some command line option.

For now I've hard coded another library in the sources, added `libSDL2.so` in my case, and was able to run a game coded in C with mir!

**Comment by vnmakarov** [comment]
I have on my to do list to add -L and -l options to c2m and correspondingly to c2mir.h interface.  I'll try to do this it earlier than I planned.

**Comment by edubart** [comment]
I've noticed that this was implemented in https://github.com/vnmakarov/mir/commit/9616fa8b2c1cba8a48d5b0fde475ce8dd48c4b5b
Thanks!

**Comment by vnmakarov** [comment]
> I've noticed that this was implemented in [9616fa8](https://github.com/vnmakarov/mir/commit/9616fa8b2c1cba8a48d5b0fde475ce8dd48c4b5b)
> Thanks!

Sorry,  I did not write you about this because I am still thinking to implement explicitly given libraries (e.g.  libxxx.so) besides ones given by option -l (e.g. -lxxx).
