### ISSUE TITLE
[C2M] Wrong struct initialization when using empty structs 

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#202]
I've caught another bug with empty structs:
```c
#include <assert.h>

typedef struct Empty{} Empty;
typedef struct Foo{Empty e; int x;} Foo;
static Empty empty;

Foo getfoo(int x) {
  return (Foo){.e=empty, .x=x};
}

int main() {
  Foo foo = getfoo(2);
  assert(foo.x == 2);
  return 0;
}
```

Output:
```
$ c2m test.c -eg
test.c:2:9: warning -- empty struct/union
c2m: test.c:12: main: Assertion `foo.x == 2' failed.
Aborted (core dumped)
```

Changing `return (Foo){.e=empty, .x=x};` to `return (Foo){.e=(Empty){}, .x=x};` works as expected.

**Comment by rofl0r** [comment]
> return (Foo){.e=empty, x=x};

shouldnt this be `return (Foo){.e=empty, .x=x};` (dot added before x)

**Comment by edubart** [comment]
> shouldnt this be `return (Foo){.e=empty, .x=x};` (dot added before x)

Sorry I've missed the dot there when typing, but adding it the test still fails, while on GCC it works.

**Comment by vnmakarov** [comment]
Thank you for reporting this.  Empty structure and member x have the same offset and if assignment of the empty structure is done after x one, `c2m` emits zeroing all memory for Foo after the empty member.

I've fixed the issue by the following commits:
https://github.com/vnmakarov/mir/commit/d0034a3954685b24fb4d4a1c909ddfb46a885e07
https://github.com/vnmakarov/mir/commit/95ecaeee16f12e2e0cf76dfead9e8df275ecddf8

**Comment by edubart** [comment]
The fix worked, thanks!
