### ISSUE TITLE
Using -O2 in c2m maybe has a bug about string literal from two different modules.

### ISSUE THREAD

**Issue by dztall** [vnmakarov/mir#211]
```c
//A.c
int main(int argc, char *argv[])
{
    Function_Of_Other_Module();
    printf("8\n");
    return 0;
}
```
```c
//B.c
void Function_Of_Other_Module()
{
    printf("9\n");
}
```

Compiling and running above with `./c2m -O2 A.c B.c -eg` command prints
9
9

where `./c2m -O0 A.c B.c -eg` or `./c2m -O1 A.c B.c -eg` command prints 
9
8

- OS is Ubuntu 20.04 LTS on windows subsystem
- CPU is  AMD Ryzen 9 5950X 16-Core Processor
- c2m is built from MIR 0.1.0 released source code

Thank you.

**Comment by vnmakarov** [comment]
Thank you very much for reporting this.  I am confirming the bug.
It seems the problem is in renaming during inlining.

I'll try to fix this on the next week and probably will create a new sub-release.

**Comment by vnmakarov** [comment]
I've fixed this bug.  It is pretty serious one.  The fixes are on master and v_0_1 branches.
