### ISSUE TITLE
Unable to compile MIR text generated by C2M when using empty structs and crashes

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#216]
Test case:
```c
typedef struct Foo{} Foo;
int f(Foo foo) {
    return 0;
}
int main(void) {
    return f((Foo){});
}
```

This is the output:
```shell
$ c2m test.c -w -eg
OK!
$ c2m test.c -w -S
$ c2m test.mir -w -eg
ln 3: invalid block arg size
ln 5: invalid block arg size
ln 6: local outside func
ln 8: undeclared name fp
ln 12: standalone endfunc
ln 17: undeclared name proto1
```

I am also getting some crashes when trying to run the text format generated by C2M, but I was unable to isolate the issue yet because I found this bug while trying to isolate, maybe the crash is related to this, here is the traceback anyway:

```
(gdb) bt
#0  0x000055e38707e5f6 in MIR_reg (
    func=<error reading variable: Cannot access memory at address 0x40>, 
    reg_name=0x55e388e5f660 "fp", ctx=0x55e388dd4530) at mir.c:2037
#1  MIR_scan_string (ctx=0x55e388dd4530, str=<optimized out>) at mir.c:5688
#2  0x000055e38700d2dd in main (argc=<optimized out>, argv=<optimized out>, env=0x7ffd7fda5a68)
    at c2mir/c2mir-driver.c:735
```

I did not provide the test case for this crash because it's a very large file, after the issue above gets fixed I can try to isolate the crash into a minor test case. I am using the MIR from master branch.

**Comment by vnmakarov** [comment]
Thank you for reporting this.  I'll try to fix this on the next week.

There are a few reported issues for the release.  I am putting fixes on the master and v_0_1 branch.  I think to make a sub-release from v_0_1 branch after some stabilization.

**Comment by vnmakarov** [comment]
I've fixed it by https://github.com/vnmakarov/mir/commit/a6a55f7f0f7c9d8da4082f1657fd266f8199bf3c

**Comment by edubart** [comment]
Thanks, this fixed this issue.

But I am hitting another issues now when trying to compile this big C filed converted to MIR text, so I've created the issue #217
