### ISSUE TITLE
[C2M] Parse statement expressions

### ISSUE THREAD

**Issue by edubart** [vnmakarov/mir#22]
Statement expression is no standard C, but an extension supported by GCC/Clang/TCC, it allows to run statements within an expression, see https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html

For my specific use case I find this extension very useful to inline arbitrary C code, where defining functions to evaluate these expressions would be more boilerplate and add complexity.

**Comment by vnmakarov** [comment]
I'll consider what GCC extensions c2m should implement.  There are too many GCC extensions.  Some extensions are easier to implement than others.  I'd say, such extension would require 2-3 weeks of work for me.  I'll try to implement it although I don't know when I find time to do this.

In any case, thank you very much for your feedback.

**Comment by dibyendumajumdar** [comment]
Hi personally I think extensions should be lower priority.

**Comment by edubart** [comment]
I would like ask to consider adding this extension one day in the long term, as it is very handy to generate arbitrary C code inside a function call argument making this extension useful for people writing languages that generates C code as it simplifies the work on the C code generator in many corner cases. I would like to use MIR one day in the language I'm working on ([Nelua](https://github.com/edubart/nelua-lang)), but mainly this is blocking me from using MIR.

@dibyendumajumdar You are doing a great work with Ravi, I use it on regular basis as Lua replacement to run many stuff including my language and maintain package for it on ArchLinux.

**Comment by dibyendumajumdar** [comment]
> @dibyendumajumdar You are doing a great work with Ravi, I use it on regular basis as Lua replacement to run many stuff including my language and maintain package for it on ArchLinux.

@edubart thank you for letting me know.

**Comment by vnmakarov** [comment]
>  would like ask to consider adding this extension one day in the long term, as it is very handy to generate arbitrary C code inside a function call argument making this extension useful for people writing languages that generates C code as it simplifies the work on the C code generator in many corner cases. I would like to use MIR one day in the language I'm working on ([Nelua](https://github.com/edubart/nelua-lang)), but mainly this is blocking me from using MIR.

OK.  I will keep it in my mind.  I don't know only when I can implement it.  I have too many other urgent things on my plate now.  But I'll implement more GCC extensions step by step while working on Ruby JIT whose code I should compile and Ruby code uses a lot of GCC extensions.

**Comment by edubart** [comment]
This was implemented in PR #196, so I'm closing the issue.
