### ISSUE TITLE
Getting function by its name

### ISSUE THREAD

**Issue by Itay2805** [vnmakarov/mir#234]
Is there a way to get a function by its name? lets say I used MIR_read to read a context from a file, how can I now get the function I want and call it? I saw there is `MIR_get_global_item` but it is not implemented....

**Comment by dibyendumajumdar** [comment]
I think this is what I do

```
MIR_item_t main_func = mir_find_function(module, func_name);
```

**Comment by Itay2805** [comment]
Yeah that's what I did as well, was just wondering if there was an existing API already but ig there isn't

**Comment by vnmakarov** [comment]
Thank you for pointing this out.  I planned to implement such function but forgot to do this.

I'll put this on my top of todo list for MIR project.
