### ISSUE TITLE
report an error: syntax error on struct (expected '<declarator>').

### ISSUE THREAD

**Issue by lydiandy** [vnmakarov/mir#241]
here is the example code:
the gcc or cc can compile and run,
but when I run: `c2m test.c -ei`, report an error: syntax error on struct (expected '<declarator>').
```
#include <stdio.h>

#define EMPTY_STRUCT_DECLARATION

struct abc {
    // EMPTY_STRUCT_DECLARATION  //without semicolon, can run with -ei/-eg
    EMPTY_STRUCT_DECLARATION;   //syntax error on struct (expected '<declarator>')
};

int main(int argc, char** argv) {
    printf("from main\n");
    return 0;
}
```

**Comment by vnmakarov** [comment]
Thank you for reporting this.
 
Empty struct declaration is not C11 standard but as I permit to use empty, I think I should permit `;` too.

I guess the patch will be ready today.

**Comment by vnmakarov** [comment]
Fixed by https://github.com/vnmakarov/mir/commit/0071a720c55d7791809858c3bc9ea3a93b1d47d6

**Comment by lydiandy** [comment]
It works, thank you @vnmakarov.
