### ISSUE TITLE
[C2M] ungetc_func should take a user supplied void pointer argument

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#25]
The `c2mir_compile()` takes `ungetc_func` function as parameter. However `ungetc_func()` implementation needs to be able to refer to some state in order to work. The standard way to allow the `ungetc_func()` to access its state is to pass a `void *` argument which is then passed to `ungetc_func()`.

At the moment the only way for `ungetc_func()` to work is to access through static lifetime data.

**Comment by vnmakarov** [comment]
OK.  I see. Thank you.  I'll do it on this week.

**Comment by vnmakarov** [comment]
I've added the state for ungetc_func.  Here is the patch https://github.com/vnmakarov/mir/compare/5f91154..f7e73aa

**Comment by dibyendumajumdar** [comment]
@vnmakarov Thank you - much appreciated!
