### ISSUE TITLE
`new_proto_*` functions should store name strings in ctx.

### ISSUE THREAD

**Issue by eliphatfs** [vnmakarov/mir#252]
`new_func_*` functions correctly store names by allocating new memory during `create_func_reg`, but `new_proto_*` functions do not. As a result, the argument names may be corrupted during `MIR_output`.

**Comment by Itay2805** [comment]
for now you can use the `_MIR_uniq_string` function to intern the wanted name

**Comment by vnmakarov** [comment]
> `new_func_*` functions correctly store names by allocating new memory during `create_func_reg`, but `new_proto_*` functions do not. As a result, the argument names may be corrupted during `MIR_output`.

Thank you for reporting this.  I've fixed this on master and v_0_x branch https://github.com/vnmakarov/mir/commit/6d8d80dbc93b1fe05bd765e3818116c849e684bf
