### ISSUE TITLE
`UMUL`/`UMULS` instructions are not recognized

### ISSUE THREAD

**Issue by mmomtchev** [vnmakarov/mir#261]
Should these two instructions exist? They are mentioned in the documentation, but not in the code.

**Comment by vnmakarov** [comment]
Such insns are not necessary as we stick to C standard semantics which now requires two complement representation of integers.  You can check a C compiler (e.g. GCC) to see that the same insns for unsigned and signed multiplication (e.g. imull or imulq for x86-64) are used,

If we needed longer result for dealing with overflow (e.g. 32-bit x 32-bit to 64-bit result) the signed and unsigned insn variants would have been needed.

**Comment by mmomtchev** [comment]
Ok, this answers my question.
