### ISSUE TITLE
implementing exceptions using MIR

### ISSUE THREAD

**Issue by Itay2805** [vnmakarov/mir#262]
Let's say I have a language I want to jit which has exceptions, exceptions basically allow to unconditionally transfer control to another point in the program which might not be known at compile time, and might be in another function entirely. How can this be done in MIR (if even possible)?

**Comment by vnmakarov** [comment]
Currently target exception handling can be done only if you implements exception with existing MIR features (e.g. by using error code for each function and checking it after each function call).

In the future, I am going to implement labels as values and indirect jumps.  Also I am thinking about implementing jret insn which is basically non-standard function call ABI.  JRET operand (e.g. register) will contain address of the return.  JRET as RET will restore callee-saved hard regs used in the function and will just jump to address given by the operand.  In this case you can implement exception more effectively (no error codes and processing them after each call, just a code section in calling function which will process return by JRET).

I am still in the process of designing this feature.  Currently I need this for my JIT for faster call/returns.  It can be ready soon (may be in month) and the implementation will be on the branch bbv.

**Comment by Itay2805** [comment]
Hmmm I guess with multiple return values it can be pretty possible to create pretty simple but effective exception emulation, thanks!
