### ISSUE TITLE
Using modules across contexts

### ISSUE THREAD

**Issue by Itay2805** [vnmakarov/mir#268]
Is is possible to share modules between contexts? imagine the following example:

- Module A is created in context A 
- Module B is created in context B (and depends on A)
- Module A and B are loaded and linked into context C 
- Module A is loaded and linked into context D 
- context C runs a function in B  which calls a function in A 
- context D runs a function in A

would something like that work? or would it be possible to make something along the lines of a creation context and a runtime context work? 

The main idea is to be able to have functions which are used across different context use the same jitted code to save on memory, but still allow each context to have its own loaded stuff. of course at any time context C and D can be freed, but the jitted code can live until context A and context B dies for each module.

One concern tho is thread safety, as each context might run on a different thread concurrently....

**Comment by Itay2805** [comment]
Yeah that kinda makes sense, the change context could be useful, I will check it out! 

In general how thread safe is the Mir api? Mainly in relation to executing Mir generated code on multiple threads?

**Comment by vnmakarov** [comment]
It is thread safe when each ctx is used only in one thread.  Any accesses to MIR internal global data (e.g. generated code pool) common for all context are implemented as critical regions.
