### ISSUE TITLE
read/write modules into one file

### ISSUE THREAD

**Issue by LambertWSJ** [vnmakarov/mir#281]
I'm working on simple RISC-V emulator [rv32emu](https://github.com/LambertWSJ/rv32emu/tree/bug) (branch: bug), and use MIR as JIT backend.

build and run `./rv32emu hello.elf` then save all modules [at finish](https://github.com/LambertWSJ/rv32emu/blob/bug/jit.c#L1242) emulator.

btw, each module is generated by `c2mir_compile`
```c
#define DLIST_MODULE_FOREACH(ctx, module)                         \
    for (MIR_module_t module =                                    \
             DLIST_HEAD(MIR_module_t, *MIR_get_module_list(ctx)); \
         module; module = DLIST_NEXT(MIR_module_t, module))


// jit.c:  rv_jit_free
DLIST_MODULE_FOREACH (jit->ctx, module) {
    MIR_write_module(jit->ctx, jit->cache, module);
}
```

when run `./rv32emu hello.elf` second time and [load cache](https://github.com/LambertWSJ/rv32emu/blob/bug/jit.c#L1167) via `MIR_read`, I got error.
```shell
unfinished binary MIR
```
I also try `MIR_write(ctx, jit->cache)` but still got same error.

Did I miss something before or after write modules?

**Comment by jserv** [comment]
> when run `./rv32emu hello.elf` second time and [load cache](https://github.com/LambertWSJ/rv32emu/blob/bug/jit.c#L1167) via `MIR_read`, I got error.
> ```shell
> unfinished binary MIR
> ```
> I also try `MIR_write(ctx, jit->cache)` but still got same error.

You shall provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) (MRE) instead of a complete project such as `rv32emu`. For the purpose, you might consider to modify [cjit](https://github.com/jserv/cjit) as MRE, so that people can help.

**Comment by LambertWSJ** [comment]
Sorry, I rewrite a simple program for reproduce problem.
[Gist](https://gist.github.com/LambertWSJ/f925dcc965fbd2e6c8b733016cf1d459)

This program save 2 modules into one file. and get same problem when load MIR binary file.

**Comment by LambertWSJ** [comment]
I should use `MIR_write` instead of `MIR_output_module` for each module.
then use `MIR_read` cache and re-generate machine code again.

The [Gist](https://gist.github.com/LambertWSJ/f925dcc965fbd2e6c8b733016cf1d459) is updated.

**Comment by vnmakarov** [comment]
Thank you for reporting your problem.  Your feedback is important and I should improve the documentation at least.

You can not write more two or more modules separately into the same file. MIR_write or MIR_write_module write compressed MIR representation.  When you use MIR_write module twice you will have several separately compressed MIR IRs.  MIR_read accepts only one compressed MIR IR.  I'll think what to do in order other people will not repeat this mistake again.
