### ISSUE TITLE
Question: How can i  generate mir when use MIR api ? 

### ISSUE THREAD

**Issue by LightSun** [vnmakarov/mir#283]
Hello , mir is a very good project , I like it. I want to use MIR to generate mir codes directly, for example define and use struct.
It is some like this. 
```
#include <stdlib.h>
#include <stdio.h>
struct Stu{
	int age;
	char* name;
};

void test_pointer(struct Stu* stu){
	printf("test_pointer = %s, age = %d\n", stu->name, stu->age);
}

void test_copy(struct Stu stu){
	printf("test_copy = %s, age = %d\n", stu.name, stu.age);
}
```
Can you help me ?

**Comment by vnmakarov** [comment]
Thank you for your interest in MIR project.  MIR API is described in file `MIR.md`. 

Examples how to use MIR API can be found in `mir-tests/api-*.h`.  The biggest file `api-sieve.h` contains code to create MIR erathosthenes sieve program.

**Comment by LightSun** [comment]
ok , thanks. I will try.
