### ISSUE TITLE
MIR should avoid global state

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#3]
I would like to use MIR in my project but the use of global state is a blocker for me.

If you are willing to take patches I can work on eliminating global state at least from the core MIR module.

**Comment by vnmakarov** [comment]
Thank you for your proposal.

I should say the project is in very active development.  A lot of things do not work.  I have also a lot of code which is not in the repository.  Introducing global state by your patch would create a lot of conflicts.
But I'll try to add the global state myself on the next week. It will be easier for me.

**Comment by dibyendumajumdar** [comment]
Okay no problem.

**Comment by vnmakarov** [comment]
I removed the global state.  I probably will work on the implementation more (as it introduces 3% compilation speed penalty) but the API will not change.

Also I'd like to keep API simple so no any nested contexts.
