### ISSUE TITLE
Accessing an externally defined C++ data structure 

### ISSUE THREAD

**Issue by sletz** [vnmakarov/mir#311]
I need to access an externally defined C++ data structure, like the following one, to be created and filled by another part of the program, add then accessed in the MIR code. Is that possible, and if yes using which API ?

```
struct Soundfile {
    void* fBuffers; // will correspond to a double** or float** pointer chosen at runtime
    int* fLength;   // length of each part (so fLength[P] contains the length in frames of part P)
    int* fSR;       // sample rate of each part (so fSR[P] contains the SR of part P)
    int* fOffset;   // offset of each part in the global buffer (so fOffset[P] contains the offset in frames of part P)
    int fChannels;  // max number of channels of all concatenated files
    int fParts;     // the total number of loaded parts
    bool fIsDouble; // keep the sample format (float or double)
}
```

**Comment by sletz** [comment]
I found the solution.

**Comment by LightSun** [comment]
@sletz how to do?

**Comment by sletz** [comment]
@LightSun have a look at https://github.com/grame-cncm/faust/blob/master-dev/compiler/generator/interpreter/fbc_mir_compiler.hh, see use of `fSoundArrayTable`, `fSoundTableID` and `fMIRSoundTable`.

**Comment by LightSun** [comment]
@sletz ok, thanks. but It seem that use structure just as a pointer.

**Comment by LightSun** [comment]
@sletz I found how to use member of stuct, But I can't find how to create struct. Do you have a demo?

**Comment by sletz** [comment]
Nope.

**Comment by LightSun** [comment]
@sletz Thanks all the same.  Do you use this library to do some funny things?

**Comment by sletz** [comment]
Used in [Faust](https://faust.grame.fr).
