### ISSUE TITLE
Possible solution for passing arguments to functions on native stack?

### ISSUE THREAD

**Issue by HackLinjiuyue** [vnmakarov/mir#313]
Consider we are implementing a virtual machine for script language, and we want to call generated functions in some ways based on information we have in VM like how many arguments we want to pass. Is there a uniform way to do it like macros based on inline assembly?

**Comment by vnmakarov** [comment]
Unfortunately, you can not express in MIR to pass an arg on the stack.  MIR is not that low-level IR.  Why it is called M(edium)IR.

Call ABI in MIR is hidden to make it more portable and it is basically the target C call ABI.

Probably it can be implemented in the future by introducing hard regs in MIR (more exactly by introducing vars permanently assigned to a specific hard reg).  I am working on such MIR (and C) extension on branch bbv.

It would be nice to have inline assembly but it is too much work (it is basically implementing assemblers on 5 MIR targets).  So I can not promise this although I think frequently how it could be implemented in simpler way.

**Comment by HackLinjiuyue** [comment]
> Unfortunately, you can not express in MIR to pass an arg on the stack. MIR is not that low-level IR. Why it is called M(edium)IR.
> 
> Call ABI in MIR is hidden to make it more portable and it is basically the target C call ABI.
> 
> Probably it can be implemented in the future by introducing hard regs in MIR (more exactly by introducing vars permanently assigned to a specific hard reg). I am working on such MIR (and C) extension on branch bbv.
> 
> It would be nice to have inline assembly but it is too much work (it is basically implementing assemblers on 5 MIR targets). So I can not promise this although I think frequently how it could be implemented in simpler way.

Maybe introduce extensions that can insert some inline MIR at certain points in C2MIR?

**Comment by vnmakarov** [comment]
> Maybe introduce extensions that can insert some inline MIR at certain points in C2MIR?

It has small sense as practically nothing in MIR can not be expressed in C, e.g. when var assigned to hard reg is introduced on MIR and C level, the MIR fragment 
```
  add sp,sp,-8
  mov mem[sp], val
```
could be on C looks like
```
  sp-=8; *sp=val
```
 In opposite inline assembler would permit to use target insns not generated by MIR.

**Comment by HackLinjiuyue** [comment]
> > Maybe introduce extensions that can insert some inline MIR at certain points in C2MIR?
> 
> It has small sense as practically nothing in MIR can not be expressed in C, e.g. when var assigned to hard reg is introduced on MIR and C level, the MIR fragment
> 
> ```
>   add sp,sp,-8
>   mov mem[sp], val
> ```
> 
> could be on C looks like
> 
> ```
>   sp-=8; *sp=val
> ```
> 
> In opposite inline assembler would permit to use target insns not generated by MIR.

Yeah, you are right. It is impossible to do this ahead of time, so the practical way to do is to implement the whole VM in MIR form, which can dynamically generate calls to certain generated functions and even external functions?

**Comment by HackLinjiuyue** [comment]
I have another idea for implementing such functionality:
1. Load bytecode module
2. parse and transform it into MIR Module that based on combination of existing basic MIR functions (including bytecode modules loaded before this)
3. execute, profile, versioning and replace original compiled code
4. get full performance of JIT

**Comment by vnmakarov** [comment]
You could also compile VM bytecode to C and then translate this C code into MIR.  It might be easier than generating MIR directly.  I use this approach for CRuby MIR-based JIT

https://github.com/vnmakarov/ruby/blob/sir-mirjit/mirjit.c

In the future I'd like to have a support of debug info for C2MIR and debugging the c code compiled by C2MIR in gdb.  Although it is a long way to go.

**Comment by HackLinjiuyue** [comment]
> You could also compile VM bytecode to C and then translate this C code into MIR. It might be easier than generating MIR directly. I use this approach for CRuby MIR-based JIT
> 
> https://github.com/vnmakarov/ruby/blob/sir-mirjit/mirjit.c
> 
> In the future I'd like to have a support of debug info for C2MIR and debugging the c code compiled by C2MIR in gdb. Although it is a long way to go.

Sounds good, but it will take more time and memory for compiling twice right?

**Comment by vnmakarov** [comment]
> Sounds good, but it will take more time and memory for compiling twice right?

Yes, it requires more additional memory than additional CPU time.  Most of time still will be spent in code generation than in C->MIR translation.

As I wrote I use this approach for possible future debugging.  The same approach (C code generation) is already used by another Ruby JIT (MJIT) and debugging the C code (generated by GCC) is important feature of MJIT.  That is what differs MJIT from Shopify YJIT for which it is hard to debug generated code (it can be done only on machine insn level) ,

**Comment by HackLinjiuyue** [comment]
> > Sounds good, but it will take more time and memory for compiling twice right?
> 
> Yes, it requires more additional memory than additional CPU time. Most of time still will be spent in code generation than in C->MIR translation.
> 
> As I wrote I use this approach for possible future debugging. The same approach (C code generation) is already used by another Ruby JIT (MJIT) and debugging the C code (generated by GCC) is important feature of MJIT. That is what differs MJIT from Shopify YJIT for which it is hard to debug generated code (it can be done only on machine insn level) ,

Reasonable. Thanks for your patient and professional explanation.
