### ISSUE TITLE
Bitcasting

### ISSUE THREAD

**Issue by giann** [vnmakarov/mir#327]
Do `I2F/D/LD` and `F/D/LD2I` perform a bitcast?
If not, how can I do one? Do I need to modify my `MIR_op_t` and change it's type?

**Comment by vnmakarov** [comment]
Not they are not a bitcast operation.  It is an analog of C cast (integer to fp or fp to integer).

The only way to perform a bitcast operation in MIR is to put the value into memory as one type value and take it back as another type value.
