### ISSUE TITLE
A #define such as __MIRC__ would be useful during compilation of C code

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#33]
It would allow programs to detect that MIR is used; purpose of this macro being similar to `__GNUC__` .

**Comment by vnmakarov** [comment]
There is already macro `__mirc__` but I added additionally `__MIRC__` and described them in `c2mir/README.md`.  Here is the patch:
https://github.com/vnmakarov/mir/commit/5f180338b7f761aa00ef0aed9065f6e870a65e0f

**Comment by dibyendumajumdar** [comment]
@vnmakarov thank you. I wasn't aware of the `__mirc__` macro. If you prefer to have only one macros that is fine with me. Thank you also for documenting.
