### ISSUE TITLE
How to get offset of a variable to the stack bottom  

### ISSUE THREAD

**Issue by mttbx** [vnmakarov/mir#349]
Hi, If I allocate an object on the stack. How can I know the offset of it to the stack bottom. Thus I can create a static const stack map to do gc.

**Comment by vnmakarov** [comment]
There is MIR_ALLOCA insn for this.  It reserves stack memory of given size and returns address to it.  The stack memory is automatically freed on the function exit.

MIR_ALLOCA is analogous to C alloca.  The insn is actually used for implementing C alloca besides to stack allocation of structure or array type C variables.

**Comment by mttbx** [comment]
Thank you.
