### ISSUE TITLE
Add Apple Silicon CI support

### ISSUE THREAD

**Issue by addr2line** [vnmakarov/mir#391]
ref: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

GitHub now supports Apple ARM chips for free CI instances for open source projects. Should we consider adding CI for it?

**Comment by vnmakarov** [comment]
Thank you for pointing this out.  I've added github action for apple silicon.

It helped me to find and fix building MIR for recent arm64 Mac OS (I used the older version of M1 MAC OS) and fix a test which should not work on M1.

The only problem for me to actively use github actions is that my month quota is not enough even when I do just small number of pushes per month.

**Comment by addr2line** [comment]
Wow, thanks for your quick response!
