### ISSUE TITLE
CMake build broken with 9b7aa03

### ISSUE THREAD

**Issue by ningvin** [vnmakarov/mir#395]
9b7aa03 renamed `mir-run` and related files to `mir-bin-run`. While this change was reflected in `GNUmakefile`, `CMakeLists.txt` still refers to the now missing `mir-run.c`. As a result, mir can no longer be built with CMake.

**Comment by vnmakarov** [comment]
Thank you for reporting this.  Fixed by 927e9d0f2012b9843548f1da83f9c1535f857b74.

**Comment by ningvin** [comment]
Can confirm, problem is fixed
