### ISSUE TITLE
Segmentation fault when compiling C program

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#4]
One of my JIT backends in Ravi generates C code which is then JIT compiled. I tried running the sieve generated code through c2mir but got a crash.

Attached in the input file.
[sieve.txt](https://github.com/vnmakarov/mir/files/3489439/sieve.txt)

**Comment by vnmakarov** [comment]
c2mir is simply not finished yet.  I guess it will be ready in 2-3 month.   The bigger challenge will be reaching a bootstrap.  I even can not say when will it happen.

Practically all the project code is not ready and in development stage.  Therefore I put the disclaimer in README.md.

**Comment by dibyendumajumdar** [comment]
Yes of course I knew that, but I wasn't sure how complete c2mir is, so I gave it a try anyway.
Please treat this as a test case.

**Comment by dibyendumajumdar** [comment]
Update: this one still causes a crash.

**Comment by dibyendumajumdar** [comment]
I was able to create the small snippet that crashes:

```
typedef unsigned char lu_byte;
typedef struct GCObject GCObject;
#define CommonHeader    GCObject *next; lu_byte tt; lu_byte marked
struct GCObject {
  CommonHeader;
};
```

**Comment by vnmakarov** [comment]
Thank you for the report (it seems I already have this bug in my work pipeline).  I've just fixed it for you but I should say that the project is under active development yet.

A lot of things should be done.  Besides functionality, there are performance issues, e.g. C2MIR generated code is currently very ineffective (e.g. generating a lot of dead code and a lot of jumps).  Although MIR generator fixes some of the performance issues but not all of them.

When I start to use it for Ruby JIT implementation, it will be a flag that it achieved some usability.  It guess it will not happen soon as from October to April I'll have to work on completely different project.

**Comment by dibyendumajumdar** [comment]
@vnmakarov  No worries thank you for fixing the bug and for the tremendous work. We have to wait for good things!
