### ISSUE TITLE
how to make recursion?

### ISSUE THREAD

**Issue by inner100p** [vnmakarov/mir#45]
Приветствую
Если я правильно понял документацию по поводу инструкции вызова
>  * The first operand is a prototype reference operand
>  * The second operand is a called function address

Но не нашел как эти данные получить...
Или же для этого можно передать в "MIR_new_insn" два поля "MIR_item_t::proto" and "MIR_item_t::addr"? Но разве addr, пока фун-ция не закончена, валидный?
Например
`MIR_item_t foo = MIR_new_func( ctx, "foo", 0, NULL, 1, MIR_T_I32, "bar" );`

`	MIR_reg_t bar = MIR_reg( ctx, "bar", foo->u.func );`
	
`	MIR_label_t finish = MIR_new_label( ctx );`
	
`	// if( bar <= 0 ) goto finish;`
`	MIR_append_insn( ctx, foo, MIR_new_insn( ctx, MIR_BLES`
		
`		, MIR_new_label_op( ctx, finish )`
`		, MIR_new_reg_op( ctx, bar )`
`		, MIR_new_int_op( ctx, 0 )`
`	) );`
		
`		// bar -= 1;`
`		MIR_append_insn( ctx, foo, MIR_new_insn( ctx, MIR_SUBS`
			
`			, MIR_new_reg_op( ctx, bar )`
`			, MIR_new_reg_op( ctx, bar )`
`			, MIR_new_int_op( ctx, 1 )`
`		) );`
		
`		// foo( bar );`
`		MIR_append_insn( ctx, foo, MIR_new_call_insn( ctx, 3`
`			, foo->proto// ???`
`			, foo->addr//  ???`
`			, MIR_new_reg_op( ctx, bar )`
`		) );`
		
`	// finish:`
`	MIR_append_insn( ctx, foo, finish );`

`MIR_finish_func( ctx );`

П.С.
Крутая библиотека, очень понравился API, похож на libjit но более простой и понятный :-)

**Comment by vnmakarov** [comment]
You should not use func addr (it is setup only during loading a module containing the function).

Instead you should use a reference operand to a finished function.
For recursion, you can create a forward item created before the function and then use reference operand to it.
```
forward_item = MIR_new_forward ("foo");
proto_item = MIR_new_proto (ctx, "foo_proto", ...); // the same result and arg types as in the function
...
MIR_new_func (ctx, "foo", ...);
MIR_new_call_insn( ctx, 3, MIR_new_ref_op (proto_item), MIR_new_ref_op (forward_item), MIR_new_reg_op( ctx, bar));
MIR_finish_func (ctx);
```
> П.С.
> Крутая библиотека, очень понравился API, похож на libjit но более простой и понятный :-)

Thank you.  It is still a long way to a release.
