### ISSUE TITLE
Question: how to output readable machine code (i.e. asm) output?

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#57]
Hi,

In my project I would like to be able to display the output from MIR at various levels; the MIR textual code, and the final machine code in assembly. I would like to capture this output rather than send to a file. I believe that the MIR text output can be sent to a file. Is there a way to get the readable disassembly of the final output? 

Thanks and regards
Dibyendu

**Comment by vnmakarov** [comment]
>  I believe that the MIR text output can be sent to a file. Is there a way to get the readable disassembly of the final output?

Yes, I use it for MIR-generator debugging.  You can see it by using option `-dg` for `c2m` or use `MIR_gen_set_debug_file` on API level.  There will be a lot of debugging/optimization info sent into `stderr` (or into file specified by the function) and you can see disassembled machine code there too.  For me the most useful part is (optimized) MIR-code right before output of the machine code.  MIR-code at this stage is just simply translated into machine insns. 

For disassembling `objdump` is used.  So it is platform specific.  I am not sure it works on OSX with their macho object format.

Also I believe something in the current mechanism could be improved but I did not think about this yet.
