### ISSUE TITLE
Adding support for SIMD datatypes and basic vector operations

### ISSUE THREAD

**Issue by rogergreen2003** [vnmakarov/mir#58]
I am interested in implementing a custom language specialized in real-time audio processing, and I have found that MIR could be a very good backend for it.

To achieve high throughput DSP in current CPU architectures, SIMD instructions should be used, so I would like to know if adding simple 128-bit vectors (4 packed floats/2 packed doubles) support to MIR is too hard.

I am talking only about supporting basic arithmetic operations like add, sub, mul and div of new MIR datatypes f32x4 and f64x2, and vector masking to enable branchless select (equivalent to C's ternary operator cond ? a : b). All of these features are currently common in x86_64 (SSE) and aarch64 (NEON).

WebAssemby is currently implementing something similar:
[https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md)

Regards.

**Comment by vnmakarov** [comment]
Thank you for interesting in MIR.

I was asked this question several times.

To be honest right now I'd like to keep MIR away from implementing vector insns.  It is not important feature for implementing lighweight tier1 JITs.

It is a very target dependent feature.   Besides arithmetic insns you need insns to pack and unpack vectors, other necessary insns.  Also why only fp insns? It would be logical to add integer vector insns too.  Also you need new vector types, a lot of target dependent machine code to implement the vector insns (call ABI could be complicated even more).  For me  next logical step would be implementing autovectorization in MIR.  It is so complicated area requiring a lot of expertise and efforts to  implement huge code,  a whole can of worms. So adding even simple vector insns would considerably complicate MIR.

I am not saying that MIR will never support vector insns.  Simply I'd like to try MIR in Ruby JIT implementation and I don't see how vector insns could help this goal.  If I see that MIR could be successful as tier2 compiler I probably will think hard about adding vector insns and which ones.

**Comment by sletz** [comment]
I agree with @vnmakarov here. We have a similar use case with [Faust](https://faust.grame.fr) and we just added a backend to use MIR, see https://github.com/vnmakarov/mir/issues/54.

The thing is that MIR seems perfect to deploy reasonably fast code using a small an easy to deploy piece of code. It you really want fast code, then you'll have to use the LLVM path.

**Comment by dibyendumajumdar** [comment]
Hi, I think MIR should avoid the complexity and bloat from vector insns because there is no need for MIR to be like LLVM. The huge strength of MIR is small size and reasonable performance. I would hate to see feature creep in MIR that then makes it lose its special asset. No point in making another LLVM.

**Comment by rogergreen2003** [comment]
Ok. Thank you for your answers. Anyway, I will try to add some basic SIMD stuff in a local branch to see if is feasible.

My purpose of using SIMD in MIR is not to create a super-optimizin compiler, but it is including the SIMD datatypes and operations in the IR itself in order to avoid external add-ons to a language as intrinsics are used in C/C++.
