### ISSUE TITLE
fatal failure in matching insn: dmov hr16, 7.0

### ISSUE THREAD

**Issue by logzero** [vnmakarov/mir#60]
So MIR_DMOV does not work with immediates on x86_64, which makes sense. What would be the proper way to load them using MIR api?

**Comment by vnmakarov** [comment]
I think it is a bug.  It should not happen.  If you have a test case, please send me to reproduce it.

MIR is a machine-independent representation.  So you can perfectly create  `dmov var, <float-constant>` and the generator should generate a machine code  for it.  You even can create `mov memory, memory` for which no one target has an insn and the generator will compile it into probably two target insns.

`dmov var, <float-constant>` is simplified to `dmov var,const-label; ... const_label:double <float-constant>` before the generator work.  So I  guess something went wrong and your test could help me to fix it.

**Comment by logzero** [comment]
Here you go: https://gist.github.com/logzero/b2ad4463d85898790d073253ac2095d4

I am trying to call some math functions using MIR_new_call_insn.

**Comment by vnmakarov** [comment]
Thank your for the test.

You missed call of MIR_load_module before MIR_link.  So MIR_link did not process the module and did not set the interface too.

I'll try to add some diagnostic for such cases if it is not difficult.

**Comment by logzero** [comment]
I see, thanks.
