### ISSUE TITLE
Calling an external vararg function

### ISSUE THREAD

**Issue by logzero** [vnmakarov/mir#63]
How many args does MIR_new_vararg_proto have to declare, just the fixed ones, or all of them?

In mir examples I see
p_printf: proto p:fmt, i32:r

The API docs say
nargs and arg_vars define only fixed arguments

**Comment by vnmakarov** [comment]
> How many args does MIR_new_vararg_proto have to declare, just the fixed ones, or all of them?

 API docs is right: nargs and arg_vars define only fixed arguments.  Moreover, nargs can be zero.

The example is old and it will not work for some target ABI (e.g. ppc64) where passing the same arguments will be different for varag and non-vararg functions. But this printf prototype works for x86_64 ABI.

The correct  prototype should be described as `proto p:fmt, ...`

**Comment by logzero** [comment]
Thanks for the clarification.

The return value (i32:r) after the arg got me confused for a moment there, as I was comparing mir with api. API takes return values before args. Need to pay more attention, lol.
