### ISSUE TITLE
WIN64 long double

### ISSUE THREAD

**Issue by logzero** [vnmakarov/mir#67]
On WIN64 long double maps to double.

There are ways to use 80bit doubles, but they aren't supported by ms libs/runtime.

How should MIR handle that? Just map LD ops to D?

**Comment by vnmakarov** [comment]
I believe my intervention is needed from here.

First of all I'd like to think how to better implement this as it might affect mir-gen.c for some approaches.

But in any case I guess I'll have a patch on this week.  I'll inform you when it is ready.  Thank you.

**Comment by vnmakarov** [comment]
I've committed a patch dealing with this issue.

Now long double ops/insns/data are changed on double ones **at MIR code creating stage** if for given ABI long double coincides with double.

Long double is a source of machine-dependence.  People should not expect that MIR code containing long double values will work the same on all targets.

**Comment by logzero** [comment]
Nice

**Comment by funny-falcon** [comment]
isn't it better to get rid of long double ? Or is strict platform C compliance a prerequisite?

**Comment by logzero** [comment]
Mir now supports low precision long doubles aka doubles. So it is not an issue.

Having higher precision long doubles on WIndows would be a nice to have feature. It's just not a high priority.

**Comment by vnmakarov** [comment]
> isn't it better to get rid of long double ? Or is strict platform C compliance a prerequisite?

Long double is mostly for C standard ABI compatibility.  I don't like that is target dependent too.  I'd like to see MIR less machine-dependent.  May be in the future C standard could have obligatory 128-bit IEEE numbers.  In that case I'd be glad to make long double a 128-bit IEEE.

In general, I'd like to see MIR is fully machine-independent.  One more machine-dependence is the number and types of function return values.  I have plans to remove any constraints here although it will require to extend target ABI for function returned values.
