### ISSUE TITLE
WIN64 doesn't support multiple return values

### ISSUE THREAD

**Issue by logzero** [vnmakarov/mir#70]
Ints are returned in RAX, floats in XMM0. Small structs are returned in RAX.

Would it be okay to just bail out in machinize?

(*MIR_get_error_func (ctx)) (MIR_call_op_error,  "Windows x86-64 does not support multiple return values.");

Or should it happen somewhere else?

**Comment by vnmakarov** [comment]
> Ints are returned in RAX, floats in XMM0. Small structs are returned in RAX.
> 

Fortunately, there are no structures on MIR-level.  It is a responsibility of MIR provider to implement structure passing according to ABI. 

> Would it be okay to just bail out in machinize?
> 

Yes, at this stage it is ok.  In the future I'd like to extend ABI to implement any number of return values.  This will remove machine-dependency for return value passing.

> (*MIR_get_error_func (ctx)) (MIR_call_op_error, "Windows x86-64 does not support multiple return values.");
> 
> Or should it happen somewhere else?

The place is ok.  But besides this place, I believe the same should be done in file `mir-x86_64.c`.  The generated code here is used for implementing FFI for the interpreter.  This file also provides C interface to the interpreter and provides a call wrapper which is used by the interpreter and the generator.  This code most probably should be adapted to WIN64 too.

Implementing ABI is a lot of work.  I appreciate what are you doing even if it were only part of ABI implementation.

**Comment by logzero** [comment]
> Implementing ABI is a lot of work. I appreciate what are you doing even if it were only part of ABI implementation.
I see it as a learning experience. I'll get to mir-x86_64.c eventually.
