### ISSUE TITLE
immediate operand in function args and return values

### ISSUE THREAD

**Issue by xujuntwt95329** [vnmakarov/mir#79]
I'm using `llvm2mir` to convert our llvm-ir into mir, and use `mir-gen` to generate machine code.

The first step `llvm-ir -> mir` works well as we don't use vectors in llvm-ir, but it fails when generating machine code for the `call insn` because there are immediate operands in the arg list.:
```
call  $p1, my_func, %37, %0, 1, %8, 1, %8
```
Same problem for the `ret insn`:
```
ret 0
```

I was wondering if there are any plan to support immediate operand as func args or return values since they are very common in C and other programming languages?

Thanks a lot !

**Comment by vnmakarov** [comment]
MIR should work with these insns.  MIR is simplified first before the generation or interpretation.  So I guess you skipped somehow the simplification pass.  I guess the following issue might help you:

https://github.com/vnmakarov/mir/issues/60

**Comment by xujuntwt95329** [comment]
I forgot to call `MIR_link` after `MIR_gen_init`, so the IR is not processed.
Thanks a lot for your help !
