### ISSUE TITLE
c2mir - while loop hangs

### ISSUE THREAD

**Issue by dibyendumajumdar** [vnmakarov/mir#9]
```
int printf(const char *s, ...);

int main(void) {
	int i = 10;

	do {
		if (i % 3 == 0)
			continue;
		if (i == 2)
			break;
		printf("%d\n", i);
	} while (i--);
	return 0;
}
```

Above program hangs - i.e. loop doesn't terminate.

**Comment by vnmakarov** [comment]
OK.  Thank you.   I'll check it.  Currently I have couple dozens of similar small tests which do not work for C2MIR.  I am on very beginning of my C2MIR debugging.

**Comment by dibyendumajumdar** [comment]
Looks like this is fixed
